#!/bin/bash

# Define variables for clarity
APP_FILE="./App.tsx"
ANALYTICS_IMPORT="import { Analytics } from '@vercel/analytics/react';"
ANALYTICS_COMPONENT="<Analytics />"

echo "--- Starting Vercel Analytics Automation ---"
echo "Targeting file: $APP_FILE"

# --- Pre-check: Ensure App.tsx exists ---
if [ ! -f "$APP_FILE" ]; then
    echo "Error: '$APP_FILE' not found in the current directory."
    echo "Please ensure you are in the root of your AgentBash project (e.g., /home/cube/agentbash)."
    exit 1
fi

# --- Step 1: Automate the addition of the Vercel Analytics import statement ---
echo "Checking for Vercel Analytics import statement..."
if grep -q "$ANALYTICS_IMPORT" "$APP_FILE"; then
    echo "Vercel Analytics import already exists in '$APP_FILE'. Skipping import addition."
else
    echo "Adding Vercel Analytics import to '$APP_FILE'..."
    # This sed command finds the last line that starts with 'import'
    # then appends the new ANALYTICS_IMPORT string *after* that line.
    sed -i "/^import .* from .*;/{:a;n;ba};i\\
$ANALYTICS_IMPORT
" "$APP_FILE"
    echo "Import added successfully."
fi

echo ""
echo "--- Manual Step Required: Insert the <Analytics /> Component ---"
echo "Automating the exact placement of the '$ANALYTICS_COMPONENT' within your React JSX structure"
echo "using simple shell scripting tools like 'sed' is highly prone to errors and can break your code."
echo "To ensure your application's integrity and correct functionality, please perform this step manually."
echo ""
echo "1.  **Open '$APP_FILE' in Visual Studio Code:**"
echo "    Run this command in your terminal:"
echo "    \`\`\`bash"
echo "    code $APP_FILE"
echo "    \`\`\`"
echo ""
echo "2.  **Locate the main 'return' statement** within your 'App' functional component."
echo "    You will typically see `return (` followed by your main JSX structure."
echo ""
echo "3.  **Carefully place the \`$ANALYTICS_COMPONENT\` component:**"
echo "    Insert \`$ANALYTICS_COMPONENT\` as a *sibling* to your main application content, "
echo "    inside the outermost JSX element returned by your `App` component. "
echo "    It should be placed just before the closing tag of your main layout element."
echo ""
echo "    --- Common Placement Examples ---"
echo ""
echo "    *   **If your `App` component returns a single `<div>` or `<main>` element (most common):**"
echo "        \`\`\`tsx"
echo "        import { Analytics } from '@vercel/analytics/react';"
echo "        // ... other imports and code"
echo ""
echo "        function App() {"
echo "          return ("
echo "            <div>"
echo "              {/* Your existing main application content (e.g., <HomePage />, <ChatInterface />) */}"
echo "              "
echo "              {/* Place <Analytics /> component here, just before the closing </div> */}"
echo "              <Analytics /> "
echo "            </div>"
echo "          );"
echo "        }"
echo ""
echo "        export default App;"
echo "        \`\`\`"
echo ""
echo "    *   **If your `App` component returns a React Fragment (`<></>` or `<React.Fragment>`):**"
echo "        \`\`\`tsx"
echo "        import { Analytics } from '@vercel/analytics/react';"
echo "        // ... other imports and code"
echo ""
echo "        function App() {"
echo "          return ("
echo "            <>"
echo "              {/* Your existing main application content */}"
echo "              "
echo "              {/* Place <Analytics /> component here, just before the closing </> */}"
echo "              <Analytics /> "
echo "            </>"
echo "          );"
echo "        }"
echo ""
echo "        export default App;"
echo "        \`\`\`"
echo ""
echo "4.  **Save** the '$APP_FILE' file in VS Code after making these changes."
echo ""
echo "--- Final Steps: Commit and Redeploy ---"
echo "Once you've manually edited and saved '$APP_FILE', you need to deploy these changes to Vercel."
echo ""
echo "1.  **Navigate to your project directory (if not already there):**"
echo "    \`\`\`bash"
echo "    cd /home/cube/agentbash"
echo "    \`\`\`"
echo ""
echo "2.  **Commit your changes to Git:**"
echo "    \`\`\`bash"
echo "    git add ."
echo "    git commit -m \"feat: Integrate Vercel Analytics component\""
echo "    git push origin main # Or the name of your main deployment branch (e.g., 'master', 'main')"
echo "    \`\`\`"
echo ""
echo "3.  **Deploy to Vercel:**"
echo "    This will trigger a new production deployment on Vercel, picking up your code changes."
echo "    \`\`\`bash"
echo "    vercel --prod"
echo "    \`\`\`"
echo "    *(This command will deploy to your linked Vercel project, which from your last output appears to be under `yashramteke55555-gmailcoms-projects/agentbash`)*"
echo ""
echo "4.  **Verify Vercel Analytics:**"
echo "    *   After the new deployment is live, visit your application's URL (e.g., `https://agentbash-72etvoah3-yashramteke55555-gmailcoms-projects.vercel.app/`)"
echo "    *   Go to your Vercel Dashboard for your `agentbash` project."
echo "    *   Check the **'Analytics'** tab to see if data is being collected after some user activity."
echo ""
echo "--- Process Completed ---"
